version: 2
jobs:
  build:
    docker:
        #- image: circleci/rust:latest
         - image: zrzka/rust-circleci
    steps:
      - checkout
      - run: cargo check --all-targets --all --bins --tests --benches
      - run: cargo test
