version: 2
jobs:
  build:
    docker:
        - image: circleci/rust:latest
    steps:
      - checkout
      - run: 
            name: "testing"
            command: cargo test
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
